concert_together/urls.py
from social.admin import admin_site
from django.urls import path, include
from social.views import Homepage

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', Homepage.as_view(), name='home'),
    path('', include('social.urls'))
]

social/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from social.views import ProfileView, UserCreationView, ConcertView, ChatView, enter_group_view, exit_group_view, \
    delete_group_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', UserCreationView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('concerti/', ConcertView.as_view(), name='concerts'),
    path('enter', enter_group_view, name='enter-group'),
    path('chat/<int:group_key>', ChatView.as_view(), name='chat-group'),
    path('exit/<int:group_key>', exit_group_view, name='exit-group'),
    path('delete/<int:group_key>', delete_group_view, name='delete-group'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    short_bio = models.TextField(null=True, max_length=255, default='I love music !!!')
    profile_photo = models.ImageField(null=True, upload_to='profile_photo', default='default_user.png')


class Artist(models.Model):
    name = models.CharField(max_length=30, unique=True, help_text="The name of the artist or band")

    def __str__(self):
        return f'{self.name}'


class Event(models.Model):
    name = models.CharField(max_length=30, help_text="The name of the event")
    date = models.DateField(help_text="The date of the event")
    location = models.CharField(max_length=50, help_text="The location of the event")
    artist = models.ManyToManyField(Artist, through="Performance")

    def __str__(self):
        return f'{self.name}, {self.date}, {self.location}, {self.artist.all()}'


class Performance(models.Model):
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)


class Group(models.Model):
    create_date = models.DateTimeField(auto_now_add=True)
    group_name = models.CharField(max_length=30)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    user = models.ManyToManyField(User, through="UserGroup")
    max_n_seat = models.PositiveSmallIntegerField(default=5)

    def __str__(self):
        return f'{self.id}, {self.create_date}, {self.group_name}, {self.event}, {self.user.all()}'


class UserGroup(models.Model):
    entry_date = models.DateTimeField(auto_now_add=True, help_text="Timestamp when the user enter the group")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    is_owner = models.BooleanField(default=False)
    needs_ride = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.id}, {self.user.username}, {self.group.group_name}'


class Message(models.Model):
    text = models.CharField(max_length=255, help_text="The text of the message")
    send_tmstmp = models.DateTimeField(auto_now_add=True)
    user_group = models.ForeignKey(UserGroup, on_delete=models.CASCADE)

social/forms.py
import time, datetime
from django import forms
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError

from social.models import UserProfile, Event, Artist, UserGroup


class SearchForm(forms.Form):
    FILTER_CHOICES = (('artist', 'Artista'), ('location', 'Luogo'), ('date', 'Data'))

    content = forms.CharField(max_length=20,
                              widget=forms.TextInput(attrs={'placeholder': 'Cerca (data Y-M-D)', 'class': 'form-control'}))
    filters = forms.ChoiceField(choices=FILTER_CHOICES,
                                widget=forms.Select(attrs={'class': 'form-select form-select-sm'}))


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2', 'email']


class AuthorProfileForm(forms.ModelForm):
    username = forms.CharField(max_length=255)
    email = forms.EmailField()

    class Meta:
        model = UserProfile
        fields = ['username', 'email', 'short_bio', 'profile_photo']

    def clean_profile_photo(self):
        upload_dir = UserProfile._meta.get_field('profile_photo').upload_to
        default_img = UserProfile._meta.get_field('profile_photo').default
        img = self.cleaned_data['profile_photo']
        if upload_dir not in img.name and default_img not in img.name:
            img.name = str(int(time.time())) + "_" + img.name
        return img


class AddEventForm(forms.ModelForm):
    artist = forms.ModelMultipleChoiceField(queryset=Artist.objects.all(),
                                            widget=forms.CheckboxSelectMultiple)
    n_seat = forms.IntegerField(min_value=0)

    class Meta:
        model = Event
        fields = ['name', 'date', 'location', 'artist']

    def clean_date(self):
        if self.cleaned_data['date'] <= datetime.date.today():
            raise ValidationError('L\' evento non può avvenire oggi o nel passato')
        else:
            return self.cleaned_data['date']


class EnterGroupForm(forms.ModelForm):
    group_id = forms.IntegerField(widget=forms.HiddenInput)

    class Meta:
        model = UserGroup
        fields = ['needs_ride']


def form_validation_error(request, form):
    msg = ""
    for field in form:
        for error in field.errors:
            msg = "%s: %s \n" % (field.label if hasattr(field, 'label') else 'Error', error)
            messages.error(request, msg)
    return msg

social/views.py
from django.contrib.auth.decorators import login_required
from social.serializers import GroupMessageSerializer
from datetime import date, datetime
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.template.defaultfilters import register
from django.urls import reverse_lazy
from django.views.generic import View, CreateView, TemplateView
from social.forms import SearchForm, AuthorProfileForm, RegisterForm, form_validation_error, AddEventForm, \
    EnterGroupForm
from social.models import UserProfile, Artist, Group, UserGroup, Message


class Homepage(TemplateView):
    template_name = 'home.html'
    success_url = reverse_lazy('home')

    def get(self, request, *args, **kwargs):

        groups = _get_groups()

        return self.render_to_response({'search_form': SearchForm(prefix='search-form-pre'),
                                        'event_form': AddEventForm(prefix='event-form-pre'),
                                        'enter_group_form': EnterGroupForm(prefix='enter-form-pre'),
                                        'groups': groups})

    def post(self, request, *args, **kwargs):
        search_form = _get_form(request, SearchForm, 'search-form-pre')
        event_form = _get_form(request, AddEventForm, 'event-form-pre')
        if search_form.is_bound and search_form.is_valid():
            keyword = search_form.cleaned_data.get('content')
            filter_choice = search_form.cleaned_data.get('filters')
            if filter_choice == 'artist':
                groups = Group.objects.all().order_by('event__date').filter(event__artist__name__icontains=keyword)
            elif filter_choice == 'location':
                groups = Group.objects.all().order_by('event__date').filter(event__location__icontains=keyword)
            elif filter_choice == 'date':
                groups = Group.objects.all().order_by('event__date').filter(
                    event__date__range=[date.today(), datetime.strptime(keyword, "%Y-%m-%d")])

            groups = _get_groups(groups)

            return self.render_to_response({'search_form': SearchForm(prefix='search-form-pre'),
                                            'event_form': AddEventForm(prefix='event-form-pre'),
                                            'enter_group_form': EnterGroupForm(prefix='enter-form-pre'),
                                            'groups': groups})
        else:
            form_validation_error(request, search_form)
        if event_form.is_bound and event_form.is_valid():
            # Create Event
            new_event = event_form.save()
            artist_list = event_form.cleaned_data.get('artist')
            for artist in artist_list:
                new_event.artist.add(Artist.objects.get(name=artist))

            # Create Group
            group_name = event_form.cleaned_data.get('name')
            n_seat = event_form.cleaned_data.get('n_seat')
            group = Group.objects.create(group_name=group_name, event=new_event, max_n_seat=n_seat)
            group.user.set([request.user], through_defaults={'is_owner': True})

            messages.success(request, 'Event added successfully')
        else:
            form_validation_error(request, event_form)
        return redirect('home')


class UserCreationView(CreateView):
    form_class = RegisterForm
    template_name = 'registration/registration.html'
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        form = RegisterForm(request.POST)
        if form.is_valid():
            valid = super(UserCreationView, self).form_valid(form)
            username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
            new_user = authenticate(username=username, password=password)
            UserProfile.objects.create(user=new_user)
            login(self.request, new_user)
            return valid
        form_validation_error(request, form)
        return redirect('register')


class ProfileView(LoginRequiredMixin, View):
    profile = None

    def dispatch(self, request, *args, **kwargs):
        self.profile, __ = UserProfile.objects.get_or_create(user=request.user)
        return super(ProfileView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        context = {'profile': self.profile}
        return render(request, 'social/profile.html', context)

    def post(self, request):
        form = AuthorProfileForm(request.POST, request.FILES, instance=self.profile)

        if form.is_valid():
            form.save()
            messages.success(request, 'Profile saved successfully')
        else:
            form_validation_error(request, form)
        return redirect('profile')


class ConcertView(LoginRequiredMixin, TemplateView):
    template_name = 'social/concert.html'
    success_url = reverse_lazy('concerts')

    def get(self, request, *args, **kwargs):
        groups = Group.objects.all().filter(user=request.user).order_by('-event__date')

        groups = _get_groups(groups)

        return self.render_to_response({'groups': groups})


class ChatView(LoginRequiredMixin, TemplateView):
    template_name = 'social/chat.html'

    def get(self, request, *args, **kwargs):
        group_id = kwargs['group_key']
        group, __ = self._get_chat(group_id)
        # return self.render_to_response({'group': group, 'messages': group_messages, 'task_id': res.id})
        group = _get_groups(group)
        return self.render_to_response({'group': group})

    def post(self, request, **kwargs):
        body = request.body.decode("utf-8")
        group_id = kwargs['group_key']
        if not body:
            group, group_messages = self._get_chat(group_id)
            ser = GroupMessageSerializer(group_messages, many=True).data
            return JsonResponse(ser, safe=False)
        else:
            group = Group.objects.get(id=group_id)
            if request.user in group.user.all():
                ug = UserGroup.objects.get(user=request.user, group=group)
                msg = Message.objects.create(text=body, user_group=ug)
                return HttpResponse(status=200)
            else:
                return redirect('home')

    def _get_chat(self, group_id):
        group = Group.objects.get(id=group_id)
        user_in_group = UserGroup.objects.all().filter(group=group)
        group_messages = Message.objects.all().filter(user_group__in=user_in_group).order_by('send_tmstmp')
        return group, group_messages


@login_required
def enter_group_view(request):
    enter_group_form = _get_form(request, EnterGroupForm, 'enter-form-pre')

    if enter_group_form.is_valid():

        group_key = enter_group_form.cleaned_data.get('group_id')
        group = Group.objects.get(id=group_key)
        needs_ride = enter_group_form.cleaned_data.get('needs_ride')

        if needs_ride:
            actual_seat = UserGroup.objects.filter(needs_ride=True).filter(group=group).count()
            if actual_seat == group.max_n_seat:
                messages.error(request, "Questo gruppo ha esaurito i posti liberi")
                return redirect('home')

        UserGroup.objects.create(user=request.user, group=group, needs_ride=needs_ride)
        messages.success(request, 'You entered the group')
    else:
        form_validation_error(request, enter_group_form)
    return redirect('home')


@login_required
def exit_group_view(request, group_key):
    group = Group.objects.get(id=group_key)
    UserGroup.objects.get(user=request.user, group=group).delete()
    messages.success(request, 'You exited from the group')
    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


@login_required
def delete_group_view(request, group_key):
    group = Group.objects.get(id=group_key)

    if group not in Group.objects.all().filter(user=request.user) or not UserGroup.objects.get(user=request.user,
                                                                                               group=group).is_owner:
        messages.error(request, 'Can\'t delete group if you are not the owner')
    else:
        group.delete()
        messages.success(request, 'Group deleted successfully')

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))


def _get_groups(groups=None):
    if groups is None:
        groups = Group.objects.all().filter(event__date__gte=date.today()).order_by('event__date')

    # check if it is a list of groups or just one group
    if hasattr(groups, '__iter__'):
        for g in groups:
            g.owner_id = UserGroup.objects.filter(is_owner=True).get(group=g).user_id
            g.seats = UserGroup.objects.filter(needs_ride=True).filter(group=g).count()
            g.tot_ppl = UserGroup.objects.filter(group=g).count()
            g.is_past = (True if date.today() > g.event.date else False)
    else:
        groups.owner_id = UserGroup.objects.filter(is_owner=True).get(group=groups).user_id
        groups.seats = UserGroup.objects.filter(needs_ride=True).filter(group=groups).count()
        groups.tot_ppl = UserGroup.objects.filter(group=groups).count()
        groups.is_past = (True if date.today() > groups.event.date else False)
    return groups


def _get_form(request, formcls, prefix):
    data = request.POST if prefix in request.POST else None
    return formcls(data, prefix=prefix)


@register.filter(name="is_in")
def is_in(user, group):
    if user in group.user.all():
        return True
    else:
        return False

social/templates/social/chat.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
    <script crossorigin src="https://unpkg.com/react@17/umd/react.production.min.js"></script>
    <script crossorigin src="https://unpkg.com/react-dom@17/umd/react-dom.production.min.js"></script>
    <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    <link rel="stylesheet" href="{% static 'social/css/form.css' %}">
    <style>

        .nopadding {
            padding: 0 !important;
            margin: 0 !important;
        }

        #messages {
            max-height: 75vh;
            overflow-y: scroll;
            margin-bottom: 1rem;
        }

        .msg-container p {
            padding: .5rem;
            margin-bottom: .5rem;
        }

        .msg-username {
            border-bottom: 0px !important;
        }

        .msg-username p {
            font-weight: bold;
            padding: 0;
            margin-bottom: 0;
        }

        .msg-text p {
            margin-bottom: 0;
            padding-bottom: 0;
        }

        .msg-tmstmp {
            text-align: right;
        }

        .msg-tmstmp p {
            color: #6c757d;
            font-size: .7rem;
        }
    </style>

{% endblock %}

{% block content %}

    <div class="container">
        {% include 'social/side_nav.html' %}
        <div class="row">
            {% include 'social/menu.html' %}
            <div class="col-11"></div>
        </div>
    </div>

    <div class="container click-outside">
        <div class="row align-items-center mb-3">
            <div class="col-9">
                <h1 id="group-title" class="display-5" style="cursor: pointer">{{ group.group_name }}</h1>
            </div>
            <div class="col-3">
                {{ group.tot_ppl }} Persone
            </div>
        </div>

        <div id="messages">
        </div>

        <div class="container row">
            <div class="input-group" style="padding: 0; margin: 0">
                <input type="text" class="form-control" id="text_input" placeholder="Scrivi nel gruppo"
                       aria-describedby="send_message">
                <button id="send_message" class="btn btn-primary" type="button"><i class="bi bi-cursor-fill"></i>
                </button>
            </div>

        </div>
    </div>

    {# GROUP MODAL #}
    <div class="modal fade" id="groupModal" tabindex="-1" style="z-index: 1070">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">{{ group.group_name }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    {% for u in group.usergroup_set.all %}
                        <div class="row gy-2 align-items-center">
                            <div class="col-4">
                                <img src="{{ MEDIA_URL }}{{ u.user.user_profile.profile_photo }}"
                                     class="rounded-circle img-fluid img-thumbnail"
                                     style=" {% if u.is_owner %} background-color: yellow {% endif %}; width: 40%; padding: .15rem"
                                     alt="profile photo">
                            </div>
                            <div class="col-4">
                                <p>{{ u.user.username }}</p>
                            </div>
                            <div class="col-2">
                                {% if u.is_owner %}
                                    <img class="img-fluid" style="width: 60%" src="{{ MEDIA_URL }}rock.png">
                                {% endif %}
                            </div>
                            <div class="col-2">
                                {% if u.needs_ride %}
                                    <img class="img-fluid" style="width: 60%" src="{{ MEDIA_URL }}car.png">
                                {% else %}
                                    <img class="img-fluid" style="width: 60%" src="{{ MEDIA_URL }}human.png">
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>




{% endblock %}

{% block javascript %}
    <script src="{% static 'social/js/menu.js' %}"></script>
    <script src="{% static 'social/js/chat.js' %}" type="text/babel"></script>
    <script type="text/babel">

        {# Open Modal #}
        var myModal = new bootstrap.Modal(document.getElementById('groupModal'))
        $("#group-title").on("click", function () {
            myModal.show()
        })


        $(document).ready(function () {
            ReactDOM.render(<Chat url="/chat/{{ group.id }}" seconds="3000"/>, document.getElementById('messages'));
        });

        const csrftoken = getCookie('csrftoken')
        $("#send_message").on("click", function () {
            fetch('/chat/{{ group.id }}', {
                method: 'POST',
                credentials: 'same-origin',
                headers: {
                    'Accept': 'application/text',
                    'X-Requested-With': 'XMLHttpRequest',
                    'X-CSRFToken': csrftoken,
                },
                body: $("#text_input").val()
            }).then(response => {
                console.log(response)
                if (response.status === 200) {
                    $("#text_input").val("")
                }

            })
        })

    </script>
{% endblock %}

social/templates/social/concert.html
{% extends 'base.html' %}
{%  load static %}

{% block content %}
    <div class="container">
        {% include 'social/side_nav.html' %}
        <div class="row">
            {% include 'social/menu.html' %}
            <div class="col-11"></div>
        </div>
    </div>

    <div class="container click-outside">
        <h2 class="display-5" style="text-align: center">I miei Concerti</h2>
        {% include 'social/event_card.html' %}
    </div>
    {% include 'social/message.html' %}

{% endblock %}


{% block javascript %}
    <script src="{% static 'social/js/menu.js' %}"></script>

{% endblock %}

social/templates/social/event_card.html
{% for g in groups %}
    <div class="card {% if g.is_past %}bg-secondary{% endif %}">
        <h5 class="card-header">{{ g.group_name }}</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-4" style="z-index: 1020">
                    <ul class="list-group" style="max-height: 15vh; overflow-y: scroll">
                        {% for artist in g.event.artist.all %}
                            <li class="list-group-item {% if g.is_past %}bg-secondary{% endif %}" style="font-size: .8rem"><strong> {{ artist.name }}</strong>
                            </li>
                        {% endfor %}
                    </ul>
                </div>

                <div class="col-8">
                    <div class="row">
                        <p class="card-title"><i>{{ g.event.location }}</i> - {{ g.event.date }}</p>
                    </div>
                    <div class="row">
                        <p>Posti auto: {{ g.seats }} / {{ g.max_n_seat }}</p>
                    </div>
                    <div class="row justify-content-evenly" style="padding-bottom: 20px">
                        <div class="col-6">
                            {% for u in g.usergroup_set.all %}
                                <img src="{{ MEDIA_URL }}{{ u.user.user_profile.profile_photo }}"
                                     class="rounded-circle img-fluid img-thumbnail"
                                     style=" {% if u.is_owner %} background-color: yellow {% endif %}; width: 30%; padding: .15rem"
                                     alt="profile photo">

                            {% endfor %}
                        </div>
                        <div class="col-6">
                            <p>{{ g.tot_ppl }} {% if g.tot_ppl > 1 %}Persone{% else %}Persona{% endif %}</p>
                        </div>
                    </div>

                    {% if not g.is_past %}
                        <div class="row justify-content-end">
                            {% if user.is_authenticated %}
                                {% if user|is_in:g %}
                                    <div class="col-4">
                                        <a href="{% url 'chat-group' g.id %}" class="btn btn-success btn-sm">Chat</a>
                                    </div>
                                    {% if g.owner_id == user.id %}
                                        <div class="col-4" style="padding: 0">
                                            {#                                        <a href="{% url 'delete-group' g.id %}" class="btn btn-danger btn-sm">Elimina</a>#}
                                            <button data-bs-toggle="modal" data-bs-target="#deleteGroupModal{{ g.id }}"
                                                    class="btn btn-danger btn-sm">Elimina
                                            </button>
                                        </div>
                                    {% else %}
                                        {# Utente appartiene al gruppo #}
                                        <div class="col-4" style="padding: 0">
                                            {#                                        <a href="{% url 'exit-group' g.id %}" class="btn btn-danger btn-sm">Esci</a>#}
                                            <button data-bs-toggle="modal" data-bs-target="#exitGroupModal{{ g.id }}"
                                                    class="btn btn-danger btn-sm">Esci
                                            </button>
                                        </div>
                                    {% endif %}

                                {% else %}
                                    <div class="col-4">
                                        {#                                    <a href="{% url 'enter-group' g.id %}" class="btn btn-primary btn-sm">Entra</a>#}
                                        <button type="button" data-bs-toggle="modal"
                                                data-bs-target="#enterGroupModal{{ g.id }}"
                                                class="btn btn-primary btn-sm">
                                            Entra
                                        </button>
                                    </div>
                                {% endif %}
                            {% else %}
                                <div class="col-4">
                                    <a href="{% url 'register' %}" class="btn btn-primary btn-sm">Entra</a>
                                </div>
                            {% endif %}
                        </div>
                    {% endif %}
                </div>
            </div>

        </div>

        <!-- Enter Group Modal -->
        <div class="modal fade" id="enterGroupModal{{ g.id }}" tabindex="-1" aria-labelledby="enterGroupLabel"
             aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-body" style="text-align: center">
                        <form id="enter-form{{ g.id }}" method="post" action="{% url 'enter-group' %}">
                            {% csrf_token %}
                            <p>Vuoi entrare in questo gruppo ?</p>
                            <label id="{{ enter_group_form.needs_ride.html_name }}">Ti serve un passaggio ?</label>
                            <input type="checkbox" name="{{ enter_group_form.needs_ride.html_name }}" checked="">
                            <input type="hidden" name="{{ enter_group_form.group_id.html_name }}" value="{{ g.id }}">

                        </form>
                    </div>
                    <div class="modal-footer justify-content-center">
                        <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Annulla</button>
                        <button type="submit" name="{{ enter_group_form.prefix }}" class="btn btn-primary btn-sm"
                                form="enter-form{{ g.id }}">Conferma
                        </button>
                    </div>
                </div>
            </div>
        </div>

        <!-- Exit Group Modal -->
        {% include 'social/simple_modal.html' with modal_name="exitGroupModal" id=g.id body_content="Vuoi uscire da questo gruppo ?" action_url="exit-group" %}

        <!-- Delete Group Modal -->
        {% include 'social/simple_modal.html' with modal_name="deleteGroupModal" id=g.id body_content="Vuoi eliminare questo gruppo ?" action_url="delete-group" %}

    </div>

    <hr>
{% endfor %}

social/templates/social/menu.html
{% extends 'base.html' %}

{% block head %}
{% endblock %}

{% block content %}
    <div class="col-1 container-fluid align-self-center" style="cursor: pointer" id="openMenu">
        <i class="bi bi-music-note-list" style="font-size: 2rem; color: blue;"></i>
    </div>

{% endblock %}

social/templates/social/message.html
{% for message in messages %}
    <div class="alert alert-{% if message.level_tag == 'error' %}danger
                            {% else %}{{ message.level_tag }} {% endif %}
                            alert-dismissible fade show" role="alert" style="position: fixed; bottom: 10px; z-index: 1080; text-align: center; width: 100%; margin: auto;">
        <p style="margin: 0">{{ message | safe }}</p>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}

social/templates/social/search_form.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
        <link rel="stylesheet" href="{% static 'social/css/form.css' %}">
{% endblock %}

{% block content %}

    <form class="search_form col" style="padding-bottom: 20px" method="post">
        <div class="container row p-1 form_content">
            {% csrf_token %}
            <div class="col-7 ">
                {{ search_form.content }}
            </div>
            <div class="col-4">
                {{ search_form.filters }}
            </div>
            <div class="col-1">
                <button type="sumbit" name="{{ search_form.prefix }}" class="btn btn-primary btn-circle"><i class="bi bi-search" style="font-size: 1rem"></i></button>
            </div>
        </div>
    </form>

{% endblock %}

social/templates/social/simple_modal.html
<div class="modal fade" id="{{ modal_name }}{{id}}" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-body" style="text-align: center">
                {{ body_content}}
            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Annulla</button>
                <a href="{% url action_url id %}" type="button" class="btn btn-primary btn-sm">Conferma</a>
            </div>
        </div>
    </div>
</div>